from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index),
    url(r'^userslhdindia/$', views.userslhdindia),
    url(r'^addmoneytowallet/$', views.addmoneytowallet),
    url(r'^checkout/$',views.checkout),
    url(r'^confirmationafterplacement/$',views.confirmationafterplacement),
    url(r'^oopsonlinepayment/$',views.oopsonlinepayment),
    url(r'^oopsofferover/$',views.oopsofferover),
    url(r'^oopsinsufficientcredit/$',views.oopsinsufficientcredit),
    url(r'^creditotpverify/$',views.creditotpverify),
    url(r'^verifyingotp/$',views.verifyingotp),
    url(r'^online_payment_successfull/$',views.online_payment_successfull),
    url(r'^online_payment_cancel/$',views.online_payment_cancel),
    url(r'^onlinepaycancel/$',views.onlinepaycancel),
    url(r'^myorderdetail/(?P<order_number>.+)/$', views.myorderdetail),
    url(r'^offerindex/(?P<offer_id>.+)/(?P<offer_day>.+)/$', views.offerindex),
    url(r'^contactus/$',views.contactus),
    url(r'^team/$',views.team),
    url(r'^adminloginpage/$', views.adminloginpage),
    url(r'^adminlogin/$', views.adminlogin),
    url(r'^partnerloginpage/$', views.partnerloginpage),
    url(r'^partnerlogin/$', views.partnerlogin),
    url(r'^myadmin/$', views.myadmin),
    url(r'^myadmin/printorder/(?P<order_number>.+)/$', views.printorder),
    url(r'^myadmin/updatedashboard/$', views.updatedashboard),
    url(r'^get_offerdata/$', views.get_offerdata),
    url(r'^apply_for_credit/$', views.apply_for_credit),
    url(r'^cancel_order_by_customer/(?P<order_number>.+)/$', views.order_cancel_confirm_page),
    url(r'^order_cancel_by_customer/(?P<order_number>.+)/$', views.order_cancel_by_customer),

    url(r'^cartajaxreload/$', views.cartajaxreload),
    url(r'^checkoutcartajaxreload/$', views.checkoutcartajaxreload),
    url(r'^additemtocart/$', views.additemtocart),
    url(r'^subtractitemtocart/$', views.subtractitemtocart),
    url(r'^clearsession/$', views.clearsession),
    url(r'^checkoutpage/$', views.checkoutpage),
    url(r'^infoajaxreload/$', views.infoajaxreload),
    url(r'^applycoupon/$', views.applycoupon),
    url(r'^applyewallet/$', views.applyewallet),
    url(r'^removewallet_amount/$', views.removewallet_amount),

    # foodpanda api's
    url(r'^foodpanda/catalog/$', views.foodpanda_catalog),

    # admin panel/applicationsetup urls
    url(r'^myadmin/applicationsetup/$', views.applicationsetup),
    url(r'^myadmin/checkonlineorderpage/$', views.checkonlineorderpage),
    url(r'^myadmin/checkonlineorder/$', views.checkonlineorder),

    # order placement --> order placement
    url(r'^placeorder/$', views.placeorder),
    url(r'^myadmin/orderaddbranch/(?P<order_number>.+)/$',
        views.orderaddbranch),
    url(r'^myadmin/orderaccepted/(?P<order_number>.+)/$', views.orderaccepted),
    url(r'^myadmin/orderadddel/(?P<order_number>.+)/$', views.orderadddel),
    url(r'^myadmin/orderdelivered/(?P<order_number>.+)/$',
        views.orderdelivered),
    url(r'^myadmin/ordercancelled/(?P<order_number>.+)/$',
        views.ordercancelled),
    url(r'^myadmin/orderdetail/(?P<order_number>.+)/$', views.orderdetail),
    url(r'^myadmin/updateordercart/(?P<order_number>.+)/$',
        views.updateordercart),
    url(r'^ajaxcheckitem/(?P<keyword>.+)/$', views.ajaxcheckitem),
    url(r'^ajaxcheckitem_counter/(?P<keyword>.+)/$', views.ajaxcheckitem),
    url(r'^ajaxcheckitem_outside/(?P<keyword>.+)/$', views.ajaxcheckitem),
    url(r'^ajaxcheckitem_callcenter/(?P<keyword>.+)/$', views.ajaxcheckitem),
    url(r'^myadmin/additemtoordercart/$', views.additemtoordercart),
    url(r'^myadmin/subtractitemtoordercart/$', views.subtractitemtoordercart),
    url(r'^myadmin/updatediscountandtax/$', views.updatediscountandtax),
    url(r'^myadmin/editorder/(?P<order_number>.+)/$', views.editorder),
    url(r'^myadmin/dashboard/searchorder/$', views.searchorder),
    url(r'^myadmin/allorder/update_advance_pay/$', views.update_advance_pay),


    # applicationsetup --> admin urls
    url(r'^myadmin/applicationsetup/admin/$', views.applicationsetup_admin),
    url(r'^myadmin/adduserpage/$', views.adduserpage),
    url(r'^myadmin/createuser/$', views.createuser),
    url(r'^myadmin/edituserpage/(?P<loginid>.+)/$', views.edituserpage),
    url(r'^myadmin/edituser/(?P<db_loginid>.+)/$', views.edituser),
    url(r'^myadmin/manage_images_description/$', views.manage_images_description),
    url(r'^myadmin/manage_app_carousel/$', views.manage_app_carousel),
    url(r'^myadmin/delete_app_carousel/(?P<image_code>.+)/$', views.delete_app_carousel),


    # applicationsetup --> customer urls
    url(r'^myadmin/applicationsetup/customer/$',
        views.applicationsetup_customer),
    url(r'^myadmin/addcustomerpage/$', views.addcustomerpage),
    url(r'^myadmin/createcustomer/$', views.createcustomer),
    url(r'^myadmin/edit_customer_info/$', views.edit_customer_info),
    url(r'^export_customer/xls/$', views.export_customers_xls, name='export_customers_xls'),


    # applicationsetup --> menu urls
    url(r'^myadmin/applicationsetup/menu/$', views.applicationsetup_menu),
    url(r'^myadmin/additempage/$', views.additempage),
    url(r'^myadmin/createitem/$', views.createitem),
    url(r'^myadmin/edititempage/(?P<item_id>.+)/$', views.edititempage),
    url(r'^myadmin/edititem/(?P<item_id>.+)/$', views.edititem),
    url(r'^myadmin/deleteitem/(?P<item_id>.+)/$', views.deleteitem),
    url(r'^myadmin/updatesubcategories/$', views.updatesubcategories),

    # myadmin --> NewOrder urls
    url(r'^myadmin/neworder/$', views.myadmin_neworder),
    url(r'^myadmin/placeneworder/$', views.neworderplacing),
    url(r'^ajaxcheckcustomer/$', views.ajaxcheckcustomer),

    # applicationsetup --> ordersource
    url(r'^myadmin/applicationsetup/ordersource/$', views.ordersource),
    url(r'^myadmin/addordersource/$', views.addordersource),
    url(r'^myadmin/deleteordersource/(?P<source_id>.+)/$',
        views.deleteordersource),

    # applicationsetup --> Restricted Areas
    url(r'^myadmin/applicationsetup/restrictedareas/$', views.restrictedareas),
    url(r'^myadmin/addrestrictedarea/$', views.addrestrictedarea),
    url(r'^myadmin/removerestrictedarea/(?P<area_id>.+)/$',
        views.removerestrictedarea),

    # applicationsetup --> Manage Waiters
    url(r'^myadmin/applicationsetup/managewaiter/$', views.managewaiter),
    url(r'^myadmin/addnewwaiter/$', views.addnewwaiter),
    url(r'^myadmin/removewaiter/(?P<waiter_id>.+)/$',
        views.removewaiter),

    # applicationsetip --> manage Tables
    url(r'^myadmin/applicationsetup/managetables/$', views.managetables),
    url(r'^myadmin/addnewtable/$', views.addnewtable),
    url(r'^myadmin/edittable/$', views.edittable),
    url(r'^myadmin/removetable/(?P<table_id>.+)/$', views.removetable),

    # applicationsetup --> item_category urls
    url(r'^myadmin/applicationsetup/itemcategory/$',
        views.applicationsetup_item_category),
    url(r'^myadmin/additemcategorypage/$', views.additemcategorypage),
    url(r'^myadmin/createitemcategory/$', views.createitemcategory),
    url(r'^myadmin/edititemcategorypage/(?P<item_category_id>.+)/$',
        views.edititemcategorypage),
    url(r'^myadmin/edititemcategory/(?P<item_category_id>.+)/$',
        views.edititemcategory),
    url(r'^myadmin/deleteitemcategory/(?P<item_category_id>.+)/$',
        views.deleteitemcategory),
    url(r'^myadmin/manageitemsubcategory/(?P<item_category_id>.+)/$',
        views.manageitemsubcategory),
    url(r'^myadmin/createsubcategory/(?P<item_category_id>.+)/$',
        views.createsubcategory),
    url(r'^myadmin/deletesubcategory/(?P<subcategory_id>.+)/(?P<category_id>.+)/$',
        views.deletesubcategory),

    # applicationsetup --> membership urls
    url(r'^myadmin/applicationsetup/membership/$',
        views.applicationsetup_membership),
    url(r'^myadmin/addmembershippage/$', views.addmembershippage),
    url(r'^myadmin/createmembership/$', views.createmembership),
    url(r'^myadmin/editmembershippage/(?P<membership_id>.+)/$',
        views.editmembershippage),
    url(r'^myadmin/editmembership/(?P<db_membership_id>.+)/$',
        views.editmembership),
    url(r'^myadmin/deletemembership/(?P<membership_id>.+)/$',
        views.deletemembership),

    # applicationsetup --> online_user urls
    url(r'^myadmin/applicationsetup/online_users/$',
        views.applicationsetup_online_users),
    url(r'^myadmin/addonlineuserpage/$', views.addonlineuserpage),
    url(r'^myadmin/createonlineuser/$', views.createonlineuser),
    url(r'^myadmin/editonlineuserpage/(?P<phone>.+)/$',
        views.editonlineuserpage),
    url(r'^myadmin/editonlineuser/(?P<db_phone>.+)/$',
        views.editonlineuser),
    url(r'^myadmin/edituserslhdindia/(?P<db_phone>.+)/$',
        views.edituserslhdindia),
    url(r'^export_users/xls/$', views.export_onlineusers_xls, name='export_users_xls'),

    # applicationsetup --> Partner urls
    url(r'^myadmin/applicationsetup/partner/$',
        views.applicationsetup_partner),
    url(r'^myadmin/addpartnerpage/$', views.addpartnerpage),
    url(r'^myadmin/createpartner/$', views.createpartner),
    url(r'^myadmin/editpartnerpage/(?P<partner_loginid>.+)/$',
        views.editpartnerpage),
    url(r'^myadmin/editpartner/(?P<db_partner_loginid>.+)/$',
        views.editpartner),
    url(r'^myadmin/deletepartner/(?P<partner_id>.+)/$',
        views.deletepartner),
    url(r'^myadmin/applicationsetup/partnermenu/(?P<partner_loginid>.+)/$',
        views.applicationsetup_partnermenu),
    url(r'^myadmin/createpartneritem/(?P<partner_loginid>.+)/$',
        views.createpartneritem),
    url(r'^myadmin/deletepartneritem/(?P<item_id>.+)/$',
        views.deletepartneritem),
    url(r'^partnermenuajaxreload/$', views.partnermenuajaxreload),

    # applicationsetup --> Coupons urls
    url(r'^myadmin/applicationsetup/coupons/$',
        views.applicationsetup_coupans),
    url(r'^myadmin/addcouponpage/$', views.addcouponpage),
    url(r'^myadmin/createcoupons/$', views.createcoupons),
    url(r'^myadmin/editcouponspage/(?P<coupons_id>.+)/$',
        views.editcouponspage),
    url(r'^myadmin/editcoupons/(?P<coupons_id>.+)/$',
        views.editcoupons),
    url(r'^myadmin/deletecoupons/(?P<coupons_id>.+)/$',
        views.deletecoupons),
    url(r'^myadmin/couponinfo/(?P<prefix>.+)/(?P<suffix>.+)/$',
        views.couponinfo),
    url(r'^myadmin/unblockcoupon/(?P<coupon_number>.+)/$',
        views.unblockcoupon),

    # applicationsetup --> Manage Promotion urls
    url(r'^myadmin/applicationsetup/managepromotion/$',
        views.applicationsetup_managepromotion),
    url(r'^myadmin/promotionvideo/$', views.promotionvideo),
    url(r'^myadmin/addpromotionimage/$', views.addpromotionimage),
    url(r'^myadmin/deletepromotionimage/(?P<image_id>.+)/$',
        views.deletepromotionimage),

    # applicationsetup --> Manage News & Events urls
    url(r'^myadmin/applicationsetup/manage_news_and_events/$',
        views.manage_news_and_events),
    url(r'^myadmin/add_news_event/$', views.add_news_event),
    url(r'^myadmin/delete_news_and_event/(?P<news_event_id>.+)/$',
        views.delete_news_and_event),
    url(r'^myadmin/edit_news_event/$', views.edit_news_event),

    # applicationsetup --> Offers urls
    url(r'^myadmin/applicationsetup/offers/$', views.applicationsetup_offers),
    url(r'^myadmin/addofferpage/$', views.addofferpage),
    url(r'^myadmin/createoffer/$', views.createoffer),
    url(r'^myadmin/editofferpage/(?P<offer_id>.+)/$', views.editofferpage),
    url(r'^myadmin/editoffer/(?P<offer_id>.+)/$', views.editoffer),
    url(r'^myadmin/deleteoffer/(?P<offer_id>.+)/$', views.deleteoffer),
    url(r'^myadmin/applicationsetup/offermenu/(?P<offer_id>.+)/$',
        views.applicationsetup_offermenu),
    url(r'^myadmin/createofferitem/(?P<offer_id>.+)/$',
        views.createofferitem),
    url(r'^myadmin/deleteofferitem/(?P<item_id>.+)/$',
        views.deleteofferitem),
    url(r'^offermenuajaxreload/$', views.offermenuajaxreload),


    # Counter orders and counter dashboard
    url(r'^onlinepay_at_counter/(?P<order_number>.+)/$', views.onlinepay_at_counter),
    url(r'^send_sms_at_counter/$', views.send_sms_at_counter),
    url(r'^counter_onlinepay_successful/$', views.counter_onlinepay_successful),
    url(r'^counter_payment_successful/$', views.counter_payment_successful),
    #############For Callcenter Online Pay#############
    url(r'^onlinepay_at_callcenter/(?P<order_number>.+)/$', views.onlinepay_at_callcenter),
    url(r'^send_sms_at_callcenter/(?P<order_number>.+)/$', views.send_sms_at_callcenter),
    url(r'^callcenter_payment_successful/$', views.callcenter_payment_successful),
    #############End of what started###################
    url(r'^cannot_pay_now/$', views.cannot_pay_now),
    url(r'^myadmin/counterdashboard/$', views.counterdashboard),
    url(r'^myadmin/updatecounterdashboard/$', views.updatecounterdashboard),
    url(r'^myadmin/printcounterorder/(?P<order_number>.+)/$',
        views.printcounterorder),
    url(r'^myadmin/additemtotableorder/$', views.additemtotableorder),
    url(r'^myadmin/addcustomerinfo/$', views.addcustomerinfo),
    url(r'^myadmin/billprint/(?P<order_number>.+)/$', views.billprint),
    url(r'^myadmin/addpaymode/$', views.addpaymode),
    url(r'^myadmin/subtractitemtotableorder/$',
        views.subtractitemtotableorder),
    url(r'^myadmin/assignwaiter/$', views.assignwaiter),
    url(r'^myadmin/counter/$', views.counter),
    url(r'^tableorder/$', views.tableorder),
    url(r'^countertableorder/$', views.countertableorder),
    url(r'^myadmin/placetableorder/$', views.placetableorder),
    url(r'^myadmin/finaltableorder/(?P<order_number>.+)/$',
        views.finaltableorder),
    url(r'^myadmin_counter/finaltableorder/(?P<order_number>.+)/$',
        views.finaltableorder),
    url(r'^myadmin_bcounter/finaltableorder/(?P<order_number>.+)/$',
        views.finaltableorder),
    url(r'^myadmin/counterorderdetail/(?P<order_number>.+)/$',
        views.counterorderdetail),
    url(r'^myadmin/editcounterorder/(?P<order_number>.+)/$',
        views.editcounterorder),
    url(r'^myadmin/updatecounterordercart/(?P<order_number>.+)/$',
        views.updatecounterordercart),
    url(r'^myadmin/updatecdisandtax/$', views.updatecdisandtax),
    url(r'^myadmin/printqt/$', views.printqt),
    url(r'^myadmin/orderinfo/(?P<order_number>.+)/$', views.orderinfo),
    url(r'^myadmin/addtodayexpense/$', views.addtodayexpense),
    url(r'^myadmin/addtodayexpensecollection/$',
        views.addtodayexpensecollection),
    url(r'^myadmin/removetodaycollection/$', views.removetodaycollection),
    url(r'^myadmin/removetodayexpense/$', views.removetodayexpense),
    url(r'^myadmin/paydeliveryboy/$', views.paydeliveryboy),
    url(r'^myadmin/removedelexp/$', views.removedelexp),
    url(r'^myadmin/counter/collectiondata/$', views.delboycollectiondata),
    url(r'^myadmin/counter/amountcollected/$', views.amountcollected),
    url(r'^myadmin/editdiscount_counter/$', views.editdiscount_counter),
    url(r'^myadmin/counterorder/$', views.counterorder),
    url(r'^myadmin/select_table/$', views.select_table),
    url(r'^myadmin/edit_advance_pay/$', views.edit_advance_pay),


    # login/signup urls
    url(r'^login/$', views.login),
    url(r'^signup/$', views.signup),
    url(r'^phoneforgotpassword/$', views.phoneforgotpassword),
    url(r'^otpverify/$', views.otpverify),
    url(r'^otpverifyforgot/$', views.otpverifyforgot),
    url(r'^removeonetimesorry/$', views.removeonetimesorry),
    url(r'^removeerrors/$', views.removeerrors),
    url(r'^removeoffererror/$', views.removeoffererror),

    # url's of report section of admin panel
    url(r'^allreports/$', views.allreportpage),
    url(r'^datereport/$', views.datereportpage),
    url(r'^singledayreport/$', views.singledayreportpage),
    url(r'^menusellreport/$', views.menusellreportpage),
    url(r'^searchmenusell/$', views.searchmenusell),
    url(r'^deliveryboyreport/$', views.deliveryboyreportpage),
    url(r'^searchdatewise/$', views.searchdatewise),
    url(r'^searchsingleday/$', views.searchsingleday),
    url(r'^searchdelboy/$', views.searchdelboy),
    url(r'^singledayreport/counterorder/$', views.singledayreportpage_counter),
    url(r'^searchsingleday/counter/$', views.searchsingleday_counter),
    url(r'^report/counterexpense/$', views.counterexpense_report),
    url(r'^report/countercollection/$', views.countercollection_report),
    url(r'^report/delboypayment/$', views.delboypayment_report),
    url(r'^report/searchcounterexpense/$', views.searchcounterexpense),
    url(r'^report/searchcountercollection/$', views.searchcountercollection),
    url(r'^report/searchdelboypayment/$', views.searchdelboypayment),
    url(r'^duecreditinfo/$', views.duecreditinfo),
    # url(r'^clearduecredit/(?P<order_number>.+)/$',views.clearduecredit),
    url(r'^clear_duecredits/$', views.clear_duecredits),

    # Inventry section urls
    url(r'^myadmin/applicationsetup/manage_inventry/$', views.manage_inventry),
    url(r'^myadmin/addinventoryitem/$', views.addinventoryitem),
    url(r'^myadmin/removeinventory_item/(?P<item_id>.+)/$',
        views.removeinventory_item),
    url(r'^myadmin/manage_dependency/(?P<item_id>.+)/$',
        views.manage_dependency),
    url(r'^myadmin/editinventoryitem/$',
        views.editinventoryitem),
    url(r'^myadmin/adddependency/$', views.adddependency),
    url(r'^myadmin/removedependency/(?P<dependency_id>.+)/$',
        views.removedependency),
    url(r'^myadmin/editdependecyitem/$',
        views.editdependecyitem),
    url(r'^ajaxcheckinventoryitem/(?P<keyword>.+)/$',
        views.ajaxcheckinventoryitem),
    url(r'^myadmin/purchaseinventoryitem/$',
        views.purchaseinventoryitem),

    # Advanced Counter Android app backend
    url(r'^android_get_menu/$', views.android_get_menu),
    url(r'^android_get_active_tables/$', views.android_get_active_tables),

    # Customer App Backend
    url(r'^appsignup/$', views.appsignup),
    url(r'^appstoresignup/$', views.appstoresignup),
    # url(r'^appcheckotp/$', views.appcheckotp),
    url(r'^applogin/$', views.applogin),
    url(r'^forgotpassword/$', views.forgotpassword),
    url(r'^getusermoreinfo/$', views.getusermoreinfo),
    url(r'^appgetmenu/$', views.appgetmenu),
    url(r'^appgetrunningoffers/$', views.appgetrunningoffers),
    url(r'^appchangepassword/$', views.appchangepassword),
    url(r'^appvalidatecoupon/$', views.appvalidatecoupon),

    # DeliveryBoy App Backend and Tracking URLS for web
    url(r'^deliveryapplogin/$', views.deliveryapplogin),
    url(r'^deliveryappdispatchedorders/$', views.deliveryappdispatchedorders),
    url(r'^deliveryappmarkdelivered/$', views.deliveryappmarkdelivered),
    url(r'^deliveryappcompletedorders/$', views.deliveryappcompletedorders),
    url(r'^deliveryapporderdispatch/$', views.deliveryapporderdispatch),
    url(r'^deliveryboytripupdates/$', views.deliveryboytripupdates),
    url(r'^deliveryappcatchlocation/$', views.deliveryappcatchlocation),

    url(r'^currenttracking/$', views.currenttracking),

    #Laundry Service URLS#
    url(r'^laundry_applicationsetup/$', views.laundry_applicationsetup),
    url(r'^laundry/setupratelist/$', views.laundry_setupratelist),
    url(r'^laundry/deleteratelistitem/(?P<item_code>.+)/$',views.deleteratelistitem),
    url(r'^laundry/setuplaundryplans/$', views.laundry_setuplaundryplans),
    url(r'^laundry/deletelaundryplan/(?P<plan_code>.+)/$',views.deletelaundryplan),
    url(r'^laundry/setuppickupdropslots/$', views.laundry_setuppickupdropslots),
    url(r'^laundry/deletepickupdropslot/(?P<slot_code>.+)/$',views.deletepickupdropslot),
    url(r'^laundry/$', views.laundry_index),
    url(r'^laundry/loginsignup/$', views.laundry_loginsignup),
    url(r'^laundry/bookorder/$', views.laundry_bookorder),
    url(r'^laundry/laundry_login/$', views.laundry_login),
    url(r'^laundry/laundry_signup/$', views.laundry_signup),
    url(r'^laundry/verifyotp/$', views.laundry_verifyotp),
    url(r'^laundry/otpverify/$', views.laundry_otpverify),
    url(r'^laundry/pricing/$', views.laundry_pricing),
]
