# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161105_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpforapp',
            name='otp',
            field=models.CharField(max_length=50),
        ),
    ]
