# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161120_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delboylocationreport',
            name='coordinate_info',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
