# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161120_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForDelBoyTripNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
    ]
