# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_fordelboytripnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelBoyUpdatedTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delboy_mob', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
