# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delboyupdatedtrips'),
    ]

    operations = [
        migrations.AddField(
            model_name='delboycurrentlocation',
            name='lastupdated_longitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delboycurrentlocation',
            name='lastupdated_latitude',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
