# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20161120_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='countertable',
            name='branch_name',
            field=models.CharField(default=b'MP Nagar', max_length=50),
        ),
    ]
