# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_countertable_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterorder',
            name='branch_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='counterorder',
            name='customer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='counterorder',
            name='table_no',
            field=models.CharField(max_length=50),
        ),
    ]
