# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20161207_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterorder',
            name='branch_name',
        ),
        migrations.AlterField(
            model_name='counterorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
        migrations.AlterField(
            model_name='counterorder',
            name='ordered_items',
            field=models.CharField(max_length=3500),
        ),
        migrations.AlterField(
            model_name='counterorder',
            name='table_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CounterTable'),
        ),
    ]
