# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20161207_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterorder',
            name='branch_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='counterorder',
            name='ordered_items',
            field=models.CharField(max_length=10000),
        ),
    ]
