# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20161207_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontodelboy',
            name='branch_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensecollection',
            name='branch_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paydeliveryboy',
            name='branch_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='waiter',
            name='branch_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
