# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20161208_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueCreditInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('loginid', models.CharField(max_length=50, null=True)),
                ('customer_mobile', models.CharField(max_length=50, null=True)),
                ('amount_due', models.CharField(max_length=50)),
                ('is_cleared', models.BooleanField(default=False)),
            ],
        ),
    ]
