# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_peritemratelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='peritemratelist',
            name='item_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
