# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_peritemratelist_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='peritemratelist',
            name='wash_fold_price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
