# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_peritemratelist_wash_fold_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('lot_size', models.CharField(max_length=50, null=True)),
                ('pricing_per_kg', models.CharField(max_length=50, null=True)),
                ('pricing_as_whole', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
