# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_laundryplans_plans_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundryplans',
            old_name='plans_code',
            new_name='plan_code',
        ),
    ]
