# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20161220_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupDropSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_or_drop', models.CharField(max_length=20)),
                ('slot_begins_at', models.CharField(max_length=10)),
                ('slot_ends_at', models.CharField(max_length=20)),
            ],
        ),
    ]
