# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_pickupdropslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupdropslots',
            name='slot_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
