# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_pickupdropslots_slot_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='peritemratelist',
            name='is_express',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(default=b'Not Entered', max_length=50),
        ),
    ]
