# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-21 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_item_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
