# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-21 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_appcarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcarousel',
            name='image_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
