# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-24 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_appcarousel_image_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='allorder',
            name='advance_pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='counterorder',
            name='advance_pay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='counterorder',
            name='credit_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countertable',
            name='waiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Waiter'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='branch_name',
            field=models.CharField(default=b'MP Nagar', max_length=50),
        ),
    ]
